# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2022-03-16 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(blank=True, max_length=400, null=True)),
                ('is_left_menu', models.BooleanField(default=False)),
                ('alias_name', models.CharField(blank=True, max_length=30, null=True)),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
                ('is_tree', models.BooleanField(default=False)),
                ('parent_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='backend.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='RoleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('create_date', models.DateField(blank=True, null=True)),
                ('create_by', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_date', models.DateField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Menu')),
                ('role_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.RoleGroup')),
            ],
        ),
        migrations.CreateModel(
            name='RoleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField()),
                ('create_by', models.CharField(blank=True, max_length=300, null=True)),
                ('modify_date', models.DateField(blank=True, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=300, null=True)),
                ('role_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.RoleGroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent_alias', models.CharField(blank=True, max_length=10)),
                ('type', models.CharField(choices=[('city', 'City'), ('province', 'Province'), ('country', 'Country')], max_length=15)),
                ('alias', models.CharField(blank=True, max_length=10)),
                ('loc_lat', models.CharField(blank=True, max_length=30)),
                ('loc_lon', models.CharField(blank=True, max_length=30)),
                ('continent_alias', models.CharField(blank=True, max_length=10)),
                ('continent_detail', models.CharField(blank=True, max_length=30)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='backend.UserArea')),
            ],
        ),
        migrations.CreateModel(
            name='UserExtend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pict_url', models.CharField(max_length=255)),
                ('is_suspended', models.IntegerField(choices=[(0, 'Not Suspended'), (1, 'Suspended')])),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('create_date', models.DateField()),
                ('create_by', models.CharField(blank=True, max_length=50, null=True)),
                ('email_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('is_activated', models.IntegerField(choices=[(0, 'Not Activated'), (1, 'Activated')], default=0)),
                ('activation_expired_date', models.DateField(blank=True, null=True)),
                ('activation_key', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
