# Generated by Django 3.2.13 on 2022-07-13 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0003_auto_20220429_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parent_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='parent', to='backend.menu'),
        ),
        migrations.AlterField(
            model_name='rolemenu',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.menu'),
        ),
        migrations.AlterField(
            model_name='rolemenu',
            name='role_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.rolegroup'),
        ),
        migrations.AlterField(
            model_name='roleuser',
            name='role_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.rolegroup'),
        ),
        migrations.AlterField(
            model_name='roleuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userextend',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
